export const defaultBgStyleFrom = "from-[#fff1eb]";
export const defaultBgStyleTo = "to-[#ace0f9]";

type ConditionData = {
  code: number;
  day: string;
  night: string;
  icon: number;
  bgStyleFrom: string;
  bgStyleTo: string;
};

/**
 * https://www.weatherapi.com/docs/weather_conditions.json
 */
export const conditions: ConditionData[] = [
  {
    code: 1000,
    day: "Sunny",
    night: "Clear",
    icon: 113,
    bgStyleFrom: "from-[#87CEEB]",
    bgStyleTo: "to-[#FFD700]",
  },
  {
    code: 1003,
    day: "Partly cloudy",
    night: "Partly cloudy",
    icon: 116,
    bgStyleFrom: "from-[#87CEEB]",
    bgStyleTo: "to-[#CCCCCC]",
  },
  {
    code: 1006,
    day: "Cloudy",
    night: "Cloudy",
    icon: 119,
    bgStyleFrom: "from-[#808080]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1009,
    day: "Overcast",
    night: "Overcast",
    icon: 122,
    bgStyleFrom: "from-[#B0C4DE]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1030,
    day: "Mist",
    night: "Mist",
    icon: 143,
    bgStyleFrom: "from-[#D3D3D3]",
    bgStyleTo: "to-[#C0C0C0]",
  },
  {
    code: 1063,
    day: "Patchy rain possible",
    night: "Patchy rain possible",
    icon: 176,
    bgStyleFrom: "from-[#87CEEB]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1066,
    day: "Patchy snow possible",
    night: "Patchy snow possible",
    icon: 179,
    bgStyleFrom: "from-[#F5F5F5]",
    bgStyleTo: "to-[#D3D3D3]",
  },
  {
    code: 1069,
    day: "Patchy sleet possible",
    night: "Patchy sleet possible",
    icon: 182,
    bgStyleFrom: "from-[#F0F8FF]",
    bgStyleTo: "to-[#B0C4DE]",
  },
  {
    code: 1072,
    day: "Patchy freezing drizzle possible",
    night: "Patchy freezing drizzle possible",
    icon: 185,
    bgStyleFrom: "from-[#F0F8FF]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1087,
    day: "Thundery outbreaks possible",
    night: "Thundery outbreaks possible",
    icon: 200,
    bgStyleFrom: "from-[#7EC8E3]",
    bgStyleTo: "to-[#5F5F5F]",
  },
  {
    code: 1114,
    day: "Blowing snow",
    night: "Blowing snow",
    icon: 227,
    bgStyleFrom: "from-[#F5F5F5]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1117,
    day: "Blizzard",
    night: "Blizzard",
    icon: 230,
    bgStyleFrom: "from-[#F8F8FF]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1135,
    day: "Fog",
    night: "Fog",
    icon: 248,
    bgStyleFrom: "from-[#D3D3D3]",
    bgStyleTo: "to-[#C0C0C0]",
  },
  {
    code: 1147,
    day: "Freezing fog",
    night: "Freezing fog",
    icon: 260,
    bgStyleFrom: "from-[#D3D3D3]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1150,
    day: "Patchy light drizzle",
    night: "Patchy light drizzle",
    icon: 263,
    bgStyleFrom: "from-[#F0F8FF]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1153,
    day: "Light drizzle",
    night: "Light drizzle",
    icon: 266,
    bgStyleFrom: "from-[#F0F8FF]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1168,
    day: "Freezing drizzle",
    night: "Freezing drizzle",
    icon: 281,
    bgStyleFrom: "from-[#E6E6FA]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1171,
    day: "Heavy freezing drizzle",
    night: "Heavy freezing drizzle",
    icon: 284,
    bgStyleFrom: "from-[#D8BFD8]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1180,
    day: "Patchy light rain",
    night: "Patchy light rain",
    icon: 293,
    bgStyleFrom: "from-[#87CEEB]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1183,
    day: "Light rain",
    night: "Light rain",
    icon: 296,
    bgStyleFrom: "from-[#87CEEB]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1186,
    day: "Moderate rain at times",
    night: "Moderate rain at times",
    icon: 299,
    bgStyleFrom: "from-[#87CEEB]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1189,
    day: "Moderate rain",
    night: "Moderate rain",
    icon: 302,
    bgStyleFrom: "from-[#87CEEB]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1192,
    day: "Heavy rain at times",
    night: "Heavy rain at times",
    icon: 305,
    bgStyleFrom: "from-[#4682B4]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1195,
    day: "Heavy rain",
    night: "Heavy rain",
    icon: 308,
    bgStyleFrom: "from-[#4682B4]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1198,
    day: "Light freezing rain",
    night: "Light freezing rain",
    icon: 311,
    bgStyleFrom: "from-[#F0F8FF]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1201,
    day: "Moderate or heavy freezing rain",
    night: "Moderate or heavy freezing rain",
    icon: 314,
    bgStyleFrom: "from-[#E6E6FA]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1204,
    day: "Light sleet",
    night: "Light sleet",
    icon: 317,
    bgStyleFrom: "from-[#F0F8FF]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1207,
    day: "Moderate or heavy sleet",
    night: "Moderate or heavy sleet",
    icon: 320,
    bgStyleFrom: "from-[#E6E6FA]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1210,
    day: "Patchy light snow",
    night: "Patchy light snow",
    icon: 323,
    bgStyleFrom: "from-[#F8F8FF]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1213,
    day: "Light snow",
    night: "Light snow",
    icon: 326,
    bgStyleFrom: "from-[#F8F8FF]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1216,
    day: "Patchy moderate snow",
    night: "Patchy moderate snow",
    icon: 329,
    bgStyleFrom: "from-[#F5F5F5]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1219,
    day: "Moderate snow",
    night: "Moderate snow",
    icon: 332,
    bgStyleFrom: "from-[#F5F5F5]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1222,
    day: "Patchy heavy snow",
    night: "Patchy heavy snow",
    icon: 335,
    bgStyleFrom: "from-[#E6E6FA]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1225,
    day: "Heavy snow",
    night: "Heavy snow",
    icon: 338,
    bgStyleFrom: "from-[#E6E6FA]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1237,
    day: "Ice pellets",
    night: "Ice pellets",
    icon: 350,
    bgStyleFrom: "from-[#F0F8FF]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1240,
    day: "Light rain shower",
    night: "Light rain shower",
    icon: 353,
    bgStyleFrom: "from-[#87CEEB]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1243,
    day: "Moderate or heavy rain shower",
    night: "Moderate or heavy rain shower",
    icon: 356,
    bgStyleFrom: "from-[#4682B4]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1246,
    day: "Torrential rain shower",
    night: "Torrential rain shower",
    icon: 359,
    bgStyleFrom: "from-[#1E90FF]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1249,
    day: "Light sleet showers",
    night: "Light sleet showers",
    icon: 362,
    bgStyleFrom: "from-[#F0F8FF]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1252,
    day: "Moderate or heavy sleet showers",
    night: "Moderate or heavy sleet showers",
    icon: 365,
    bgStyleFrom: "from-[#E6E6FA]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1255,
    day: "Light snow showers",
    night: "Light snow showers",
    icon: 368,
    bgStyleFrom: "from-[#F8F8FF]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1258,
    day: "Moderate or heavy snow showers",
    night: "Moderate or heavy snow showers",
    icon: 371,
    bgStyleFrom: "from-[#E6E6FA]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1261,
    day: "Light showers of ice pellets",
    night: "Light showers of ice pellets",
    icon: 374,
    bgStyleFrom: "from-[#F0F8FF]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1264,
    day: "Moderate or heavy showers of ice pellets",
    night: "Moderate or heavy showers of ice pellets",
    icon: 377,
    bgStyleFrom: "from-[#E6E6FA]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1273,
    day: "Patchy light rain with thunder",
    night: "Patchy light rain with thunder",
    icon: 386,
    bgStyleFrom: "from-[#4682B4]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1276,
    day: "Moderate or heavy rain with thunder",
    night: "Moderate or heavy rain with thunder",
    icon: 389,
    bgStyleFrom: "from-[#1E90FF]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1279,
    day: "Patchy light snow with thunder",
    night: "Patchy light snow with thunder",
    icon: 392,
    bgStyleFrom: "from-[#F8F8FF]",
    bgStyleTo: "to-[#A9A9A9]",
  },
  {
    code: 1282,
    day: "Moderate or heavy snow with thunder",
    night: "Moderate or heavy snow with thunder",
    icon: 395,
    bgStyleFrom: "from-[#E6E6FA]",
    bgStyleTo: "to-[#A9A9A9]",
  },
];
